---
name: Build

on:
  push: {}

permissions:
  contents: write

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: transform devcontainer config
        run: |
          jq 'del(.runArgs)' .devcontainer/devcontainer.json > /tmp/devcontainer.json
          mv /tmp/devcontainer.json .devcontainer/devcontainer.json
      - uses: devcontainers/ci@v0.3
        with:
          push: never
          runCmd: |
            for app in * ; do
              pushd $app
                npm install
                npm run build
              popd
            done
