---
name: Build

on:
  push: {}

permissions:
  contents: write

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: devcontainers/ci@v0.3
        with:
          push: never
          runCmd: |
            for app in */ ; do
              pushd $app
                npm clean-install
                npm run build
              popd
            done
