---
name: CI (branch)

on:
  push: {}

permissions:
  contents: write

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          jq 'del(.runArgs)' .devcontainer/devcontainer.json > /tmp/devcontainer.json
          mv /tmp/devcontainer.json .devcontainer/devcontainer.json
      - uses: devcontainers/ci@v0.3
        with:
          runCmd: pwd
          configFile: /tmp/devcontainer.json
          # runCmd: |
          #   for app in . ; do
          #     pushd $app
          #       npm run test
          #     popd
          #   done
